import React from 'react';
import { Platform, Pressable, ScrollView, View, useWindowDimensions } from 'react-native';
import { Slot, usePathname, useRouter } from 'expo-router';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { useFonts, DMSans_400Regular,DMSans_500Medium,DMSans_700Bold } from '@expo-google-fonts/dm-sans';
import { Manrope_600SemiBold,Manrope_700Bold,Manrope_800ExtraBold } from '@expo-google-fonts/manrope';
import { Home, CalendarDays, ShoppingBasket, ChartNoAxesCombined, UserRound, Sprout, ArrowUpRight, Bell, Check, Undo2 } from 'lucide-react-native';
import { QueryClient,QueryClientProvider } from '@tanstack/react-query';
import { StatusBar } from 'expo-status-bar';
import { Provider,useStore } from '../src/store';
import { C,P,H,Eyebrow,s } from '../src/ui';
const queryClient=new QueryClient();
const tabs=[{path:'/',name:'Home',icon:Home},{path:'/plan',name:'My plan',icon:CalendarDays},{path:'/grocery',name:'Groceries',icon:ShoppingBasket},{path:'/progress',name:'Progress',icon:ChartNoAxesCombined},{path:'/profile',name:'Profile',icon:UserRound}];
function Brand(){return <View style={[s.row,{gap:8}]}><View style={{backgroundColor:C.lime,width:33,height:33,borderRadius:11,alignItems:'center',justifyContent:'center'}}><Sprout size={22} color={C.ink}/></View><H size={27}>portion<P style={{color:'#8EA74B',fontSize:30}}>·</P></H></View>;}
function Shell(){const {width}=useWindowDimensions(),wide=width>=1050,router=useRouter(),path=usePathname();const {data,toast,canUndo,undo,sync,retry}=useStore();const onboarding=path==='/onboarding';return <SafeAreaView style={{flex:1,backgroundColor:C.bg}} edges={['top','left','right']}><StatusBar style="dark"/><View style={{flex:1,flexDirection:'row'}}>{wide&&!onboarding&&<View style={{width:226,padding:28,borderRightWidth:1,borderColor:C.line,backgroundColor:C.paper}}><Brand/><Eyebrow style={{marginTop:50,marginBottom:16}}>YOUR EVERYDAY, SORTED</Eyebrow><View style={{gap:8}}>{tabs.map(t=><Pressable key={t.path} accessibilityRole="tab" accessibilityState={{selected:path===t.path}} onPress={()=>router.push(t.path as any)} style={[s.row,{minHeight:50,paddingHorizontal:16,borderRadius:13,backgroundColor:path===t.path?C.lime:'transparent'}]}><t.icon size={19} color={path===t.path?C.ink:C.muted}/><P style={{fontFamily:path===t.path?'DMSans_700Bold':'DMSans_500Medium',color:path===t.path?C.ink:C.muted}}>{t.name}</P></Pressable>)}</View><View style={{flex:1}}/><View style={{backgroundColor:C.soft,borderRadius:18,padding:18,gap:12}}><Sprout size={24}/><H size={17}>Less figuring out. More feeling good.</H><P style={{fontSize:12,color:C.muted}}>Your macros, budget, and week. Working together.</P></View><View style={[s.row,{marginTop:24}]}><View style={{width:35,height:35,borderRadius:18,backgroundColor:'#F2DFCA',alignItems:'center',justifyContent:'center'}}><P style={{fontFamily:'DMSans_700Bold'}}>{data.profile.name[0]||'Y'}</P></View><View><P style={{fontFamily:'DMSans_700Bold',fontSize:12}}>{data.profile.name}</P><P style={{fontSize:10,color:C.muted}}>{data.personalized?'Your personal plan':'Exploring Portion'}</P></View></View></View>}
<View style={{flex:1}}>{!onboarding&&<View style={{paddingHorizontal:wide?40:22,paddingVertical:wide?20:14,backgroundColor:C.bg,borderBottomWidth:wide?1:0,borderColor:C.line}}><View style={s.between}>{wide?<View style={s.row}><P style={{fontSize:12,color:C.muted}}>Your space</P><P style={{color:'#B8BEB2'}}>/</P><P style={{fontSize:12}}>{tabs.find(t=>t.path===path)?.name??'Home'}</P></View>:<Brand/>}<View style={[s.row,{gap:14}]}>{!data.personalized&&<Pressable accessibilityRole="button" onPress={()=>router.push('/onboarding')} style={{backgroundColor:C.soft,borderRadius:20,paddingHorizontal:12,paddingVertical:8}}><P style={{fontSize:10,fontFamily:'DMSans_700Bold',letterSpacing:.5}}>SAMPLE WEEK <ArrowUpRight size={11}/></P></Pressable>}<Pressable accessibilityLabel="Open profile" onPress={()=>router.push('/profile')} style={{width:36,height:36,borderRadius:18,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'}}><UserRound size={17}/></Pressable></View></View>{sync&&<Pressable onPress={()=>void retry()}><P style={{fontSize:10,color:C.muted,marginTop:5,textAlign:'right'}}>{sync}</P></Pressable>}</View>}
<Slot/>{!wide&&!onboarding&&<SafeAreaView edges={['bottom']} style={{backgroundColor:C.paper,borderTopWidth:1,borderColor:C.line}}><View style={{flexDirection:'row',paddingVertical:8}}>{tabs.map(t=><Pressable key={t.path} accessibilityRole="tab" accessibilityLabel={t.name} accessibilityState={{selected:path===t.path}} onPress={()=>router.push(t.path as any)} style={{flex:1,alignItems:'center',gap:5,minHeight:48,justifyContent:'center'}}><View style={{paddingHorizontal:13,paddingVertical:4,borderRadius:14,backgroundColor:path===t.path?C.lime:'transparent'}}><t.icon size={20} color={path===t.path?C.ink:C.muted}/></View><P style={{fontSize:10,lineHeight:12,color:path===t.path?C.ink:C.muted,fontFamily:path===t.path?'DMSans_700Bold':'DMSans_400Regular'}}>{t.name}</P></Pressable>)}</View></SafeAreaView>}</View></View>{toast&&<View pointerEvents="box-none" style={{position:'absolute',bottom:100,left:22,right:22,alignItems:'center'}}><View style={{backgroundColor:C.ink,borderRadius:16,padding:16,maxWidth:520,flexDirection:'row',gap:16,alignItems:'center'}}><Check size={18} color={C.lime}/><P accessibilityLiveRegion="polite" style={{color:C.paper,flex:1,fontSize:13}}>{toast}</P>{canUndo&&<Pressable accessibilityLabel="Undo last change" onPress={undo}><Undo2 size={19} color={C.lime}/></Pressable>}</View></View>}</SafeAreaView>;}
// A native-safe inline space (keeps the sidebar headline readable on every renderer).
function brHidden(){return null;}
export default function Layout(){const [loaded,error]=useFonts({DMSans_400Regular,DMSans_500Medium,DMSans_700Bold,Manrope_600SemiBold,Manrope_700Bold,Manrope_800ExtraBold});if(!loaded&&!error)return <View style={{flex:1,backgroundColor:C.bg}}/>;return <SafeAreaProvider><QueryClientProvider client={queryClient}><Provider><Shell/></Provider></QueryClientProvider></SafeAreaProvider>;}
