import React,{useState} from 'react';
import { Pressable,ScrollView,View,useWindowDimensions } from 'react-native';
import { useRouter } from 'expo-router';
import { ArrowRight,ArrowUpRight, Sparkles,ShoppingBasket,Plus,Leaf,Check,SlidersHorizontal } from 'lucide-react-native';
import { useStore } from '../src/store';
import { C,P,H,Eyebrow,Card,Button,s,money,round } from '../src/ui';
import { MealCard,MealSheet,NutritionCard } from '../src/components';
import { Adjuster } from '../src/adjuster';
import { add,projectedDay,groceryTotal } from '../supabase/functions/_shared/engine';
import { ZERO,localDate,DAYS } from '../supabase/functions/_shared/domain';
import type { PlannedMeal } from '../supabase/functions/_shared/domain';
export default function Home(){const {data,ready}=useStore(),router=useRouter(),{width}=useWindowDimensions(),wide=width>1150;const [meal,setMeal]=useState<PlannedMeal|null>(null),[mode,setMode]=useState<'protein'|'outside'|null>(null);const day=(new Date().getDay()+6)%7,meals=data.plan.meals.filter(m=>m.day===day),actual=data.logs.filter(l=>l.date===localDate()).reduce((s,l)=>add(s,l.macros),ZERO),projected=projectedDay(data.plan,data.logs,day),budget=groceryTotal(data.plan,data.pantry)+data.manual.reduce((s,g)=>s+g.price,0);const [showAll,setShowAll]=useState(false);return <ScrollView contentContainerStyle={{padding:width>=1050?40:22,paddingTop:width>=1050?32:16,paddingBottom:40}}><View style={{maxWidth:1200,width:'100%',alignSelf:'center'}}><View style={[s.between,{alignItems:'flex-start',marginBottom:28}]}><View><Eyebrow>{new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'}).toUpperCase()}</Eyebrow><H size={width>700?42:34} style={{marginTop:8}}>Your day, in good balance.</H><P style={{color:C.muted,marginTop:10}}>A plan that fits your goals. And your actual life.</P></View>{width>700&&<View style={{backgroundColor:C.soft,borderRadius:20,paddingHorizontal:14,paddingVertical:9,flexDirection:'row',gap:7,alignItems:'center'}}><Leaf size={14}/><P style={{fontSize:11}}>One good meal at a time</P></View>}</View>
{!data.personalized&&<Pressable accessibilityRole="button" onPress={()=>router.push('/onboarding')} style={{backgroundColor:C.lime,borderRadius:18,padding:18,marginBottom:24,flexDirection:'row',alignItems:'center',gap:16}}><View style={{height:38,width:38,borderRadius:12,backgroundColor:'#FFFFFF66',alignItems:'center',justifyContent:'center'}}><Sparkles size={20}/></View><View style={{flex:1}}><P style={{fontFamily:'DMSans_700Bold',fontSize:14}}>Your macros. Your budget. Your kind of food.</P><P style={{fontSize:12,marginTop:2}}>You’re exploring a sample week. Let’s make it yours.</P></View><View style={[s.row,{gap:7}]}>{width>700&&<P style={{fontFamily:'DMSans_700Bold',fontSize:12}}>Build my week</P>}<ArrowRight size={20}/></View></Pressable>}
<View style={{flexDirection:wide?'row':'column',gap:24}}><View style={{flex:wide?1:undefined,gap:28}}><View style={{flexDirection:width>760?'row':'column',gap:20}}><View style={{flex:1.65}}><NutritionCard actual={actual} target={data.profile.targets} projected={projected}/></View><Card style={{flex:1,justifyContent:'space-between',gap:20}}><View style={s.between}><Eyebrow>WEEKLY GROCERIES</Eyebrow><ShoppingBasket size={19} color={C.muted}/></View><View><H size={38}>{money(budget)}</H><P style={{fontSize:12,color:C.muted,marginTop:6}}>of your {money(data.profile.budget).replace('.00','')} weekly budget</P><View style={{height:6,backgroundColor:C.soft,borderRadius:3,marginTop:19,overflow:'hidden'}}><View style={{height:6,borderRadius:3,backgroundColor:budget>data.profile.budget?C.orange:C.lime,width:`${Math.min(100,budget/data.profile.budget*100)}%`}}/></View><P style={{fontSize:11,color:C.muted,marginTop:9}}>{budget<=data.profile.budget?`${money(data.profile.budget-budget)} breathing room`:`${money(budget-data.profile.budget)} above your budget`}</P></View><Pressable accessibilityRole="button" onPress={()=>router.push('/grocery')} style={s.between}><P style={{fontSize:12,fontFamily:'DMSans_700Bold'}}>View grocery list</P><ArrowUpRight size={17}/></Pressable></Card></View>
<View><View style={[s.between,{marginBottom:17}]}><View style={[s.row,{gap:9}]}><H size={24}>On today’s menu</H><View style={{backgroundColor:C.soft,paddingHorizontal:8,paddingVertical:2,borderRadius:10}}><P style={{fontSize:11}}>{meals.length}</P></View></View><Pressable accessibilityRole="button" onPress={()=>router.push('/plan')} style={[s.row,{gap:5}]}><P style={{fontSize:12,color:C.muted}}>Full week</P><ArrowRight size={14} color={C.muted}/></Pressable></View><View style={{flexDirection:'row',flexWrap:'wrap',gap:18}}>{(showAll?meals:meals.slice(0,width<700?2:3)).map(m=><View key={m.id} style={{width:width<600?'100%':wide?'47.8%':'31.5%',flexGrow:1}}><MealCard meal={m} onPress={()=>setMeal(m)}/></View>)}</View>{!meals.length&&<Card><P>No meals planned for today. You can still log what you eat or personalize your schedule.</P><Button secondary style={{marginTop:16}} onPress={()=>router.push('/onboarding')}>Edit my schedule</Button></Card>}{meals.length>(width<700?2:3)&&<Pressable accessibilityRole="button" onPress={()=>setShowAll(!showAll)} style={{padding:15,alignItems:'center'}}><P style={{fontSize:12,color:C.muted}}>{showAll?'Show less':`See all ${meals.length} meals`}</P></Pressable>}</View></View>
<View style={{width:wide?278:undefined,gap:20}}><Card style={{backgroundColor:'#ECEFE3',borderColor:'#ECEFE3',gap:17,padding:23}}><View style={{width:40,height:40,borderRadius:13,backgroundColor:C.lime,alignItems:'center',justifyContent:'center'}}><Sparkles size={21}/></View><Eyebrow>THE REAL-LIFE ADJUSTER</Eyebrow><H size={27}>Plans change.{ '\n'}Your goals don’t.</H><P style={{color:'#737D6D',fontSize:13}}>Lunch out? A little low on protein? We’ll help the rest of your day fall into place.</P><Button secondary icon={false} onPress={()=>setMode('outside')} style={{backgroundColor:C.paper,justifyContent:'space-between'}}><P style={{fontSize:12,fontFamily:'DMSans_700Bold'}}>I ate something else</P></Button><Pressable accessibilityRole="button" onPress={()=>setMode('protein')} style={[s.row,{justifyContent:'center',padding:7}]}><Plus size={15}/><P style={{fontSize:12,fontFamily:'DMSans_700Bold'}}>I need more protein</P></Pressable></Card><Card style={{gap:15}}><View style={s.between}><Eyebrow>MADE FOR YOUR WEEK</Eyebrow><SlidersHorizontal size={15} color={C.muted}/></View><H size={19}>Good food. Less effort.</H>{[{label:'Protein comes first',sub:`${data.profile.targets.protein}g daily target`},{label:'Smart ingredient overlap',sub:'Less waste, more value'},{label:`${data.profile.prepSessions} prep sessions`,sub:'A little prep goes a long way'}].map(x=><View key={x.label} style={[s.row,{alignItems:'flex-start'}]}><View style={{backgroundColor:C.soft,borderRadius:10,padding:6}}><Check size={13} color='#779146'/></View><View style={{flex:1}}><P style={{fontSize:12,fontFamily:'DMSans_500Medium'}}>{x.label}</P><P style={{fontSize:11,color:C.muted}}>{x.sub}</P></View></View>)}</Card><P style={{fontSize:10,color:'#929B8A',textAlign:'center',lineHeight:16}}>Nourish your goals. Leave room for life.</P></View></View></View><MealSheet meal={meal} onClose={()=>setMeal(null)}/><Adjuster mode={mode} day={day} onClose={()=>setMode(null)}/></ScrollView>;}
