import React,{useEffect,useState} from 'react';
import { Animated,Pressable,ScrollView,View,useWindowDimensions,ActivityIndicator } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useRouter } from 'expo-router';
import { ArrowLeft,ArrowRight,Check,Sprout,Flame,Microwave,ChefHat,Blender,CookingPot,Utensils,Timer,Wind,Search } from 'lucide-react-native';
import { useStore } from '../src/store';
import { C,P,H,Eyebrow,Card,Button,Field,Chip,Stepper,s } from '../src/ui';
import { DAYS,MEALS,EQUIPMENT,PREFERENCES,DIETS,validateProfile } from '../supabase/functions/_shared/domain';
import type { Profile } from '../supabase/functions/_shared/domain';
import { INGREDIENTS } from '../supabase/functions/_shared/catalog';
import { recommendedTargets } from '../supabase/functions/_shared/engine';
import { configured } from '../src/lib/backend';
import { AuthSheet } from '../src/auth';
const titles=['What are you working toward?','Let’s find your daily energy.','Make your macros work for you.','Who’s coming to the table?','Which meals can we take off your plate?','Make room for your real week.','Good food. Comfortable budget.','What sounds like your kind of food?','A little more about how you eat.','More of what you love.','What’s in your kitchen?','How much time is on the menu?','Your week starts here.'];
const subtitles=['Every goal starts with a little everyday consistency.','Bring your own calorie target, or let us estimate a starting point.','Protein first. Plenty of flexibility for the rest.','Your macros stay personal. Everyone else gets a standard serving.','We’ll leave room in your targets for meals you plan yourself.','Pick the days you’d like us to plan.','We optimize ingredients and portions to keep groceries close to your budget.','Pick up to three things that matter most.','Your restrictions are always respected.','Search ingredients and tell us how you feel about them.','We’ll only suggest recipes you have the tools to make.','Less time deciding. More time enjoying.','A quick look before we put it all together.'];
const toggle=<T,>(list:T[],v:T)=>list.includes(v)?list.filter(i=>i!==v):[...list,v];
export default function Onboarding(){const {data,generate,session,notify}=useStore(),router=useRouter();const [profile,setProfile]=useState<Profile>(structuredClone(data.profile)),[step,setStep]=useState(0),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[calculating,setCalculating]=useState(false),[stage,setStage]=useState(0),[auth,setAuth]=useState(false),[search,setSearch]=useState(''),[customDay,setCustomDay]=useState<number|null>(null),[calculator,setCalculator]=useState(false),[age,setAge]=useState('28'),[sex,setSex]=useState<'male'|'female'>('female'),[height,setHeight]=useState('168'),[weight,setWeight]=useState('68'),[activity,setActivity]=useState(1.375);const {width}=useWindowDimensions();
  const update=(p:Partial<Profile>)=>setProfile(prev=>({...prev,...p}));
  useEffect(()=>{AsyncStorage.getItem('portion:onboarding').then(raw=>{if(raw){try{const draft=JSON.parse(raw);setProfile(draft.profile);setStep(Math.min(12,draft.step));}catch{}}}).finally(()=>setLoaded(true));},[]);
  useEffect(()=>{if(loaded)void AsyncStorage.setItem('portion:onboarding',JSON.stringify({profile,step}));},[profile,step,loaded]);
  const macroCalories=Math.round(profile.targets.protein*4+profile.targets.carbs*4+profile.targets.fat*9);
  const next=()=>{setError('');if(step===2&&Math.abs(macroCalories-profile.targets.calories)>Math.max(30,profile.targets.calories*.03)){setError('Use your calculated macro calories or adjust the grams to match your calorie target.');return;}if(step===4&&!profile.meals.length){setError('Choose at least one meal.');return;}if(step===5&&!profile.days.length){setError('Choose at least one day.');return;}setStep(Math.min(12,step+1));};
  async function build(){setError('');try{validateProfile(profile);}catch(e){setError((e as Error).message);return;}if(configured&&!session){setAuth(true);return;}setCalculating(true);setStage(0);const timer=setInterval(()=>setStage(s=>Math.min(4,s+1)),500);try{await generate(profile);setStage(5);await AsyncStorage.removeItem('portion:onboarding');await new Promise(resolve=>setTimeout(resolve,400));router.replace('/');notify(session?'Your personalized week is ready.':'Your sample plan is ready. Saved on this device.');}catch(e){setError((e as Error).message);}finally{clearInterval(timer);setCalculating(false);}}
  if(calculating)return <View style={{flex:1,justifyContent:'center',alignItems:'center',padding:30,gap:25}}><View style={{width:88,height:88,backgroundColor:C.lime,borderRadius:30,alignItems:'center',justifyContent:'center'}}><Sprout size={42}/></View><H size={36}>Building your week…</H><P style={{color:C.muted,textAlign:'center'}}>A little thought now. A delicious week ahead.</P><ActivityIndicator color={C.dark}/><View style={{gap:18,marginTop:15}}>{['Calculating your calorie and macro targets','Matching meals to your preferences','Balancing protein, carbs, and fats','Optimizing grocery overlap','Keeping the plan within budget','Building your grocery list'].map((t,i)=><View key={t} style={[s.row,{opacity:i<=stage?1:.3}]}><Check size={17} color={i<stage?'#819F3F':C.muted}/><P style={{fontSize:13}}>{t}</P></View>)}</View></View>;
  return <View style={{flex:1}}><View style={{padding:22,flexDirection:'row',alignItems:'center',gap:20,maxWidth:740,width:'100%',alignSelf:'center'}}><Pressable accessibilityLabel="Go back" onPress={()=>step>0?setStep(step-1):router.back()} style={s.step}><ArrowLeft size={19}/></Pressable><View style={{flex:1,height:5,backgroundColor:C.line,borderRadius:3}}><View style={{width:`${(step+1)/13*100}%`,height:5,backgroundColor:'#A5C550',borderRadius:3}}/></View><Eyebrow>{String(step+1).padStart(2,'0')} / 13</Eyebrow></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:24,paddingTop:26,paddingBottom:40,maxWidth:690,width:'100%',alignSelf:'center',gap:26}}><View style={{gap:14}}><Eyebrow>MAKE IT PERSONAL</Eyebrow><H size={width>700?39:33}>{titles[step]}</H><P style={{color:C.muted,fontSize:15}}>{subtitles[step]}</P></View>
{step===0&&<View style={{gap:12}}>{['Lose fat','Maintain weight','Build muscle','Eat healthier'].map((goal,i)=><Pressable accessibilityRole="radio" accessibilityState={{checked:profile.goal===goal}} key={goal} onPress={()=>update({goal})}><Card style={[s.between,{backgroundColor:profile.goal===goal?C.lime:C.paper,borderColor:profile.goal===goal?C.lime:C.line,padding:23}]}><View style={s.row}><View style={{width:38,height:38,borderRadius:13,backgroundColor:'#FFFFFF80',alignItems:'center',justifyContent:'center'}}>{[<Flame size={23}/>,<Sprout size={23}/>,<Utensils size={23}/>,<ChefHat size={23}/>][i]}</View><H size={20}>{goal}</H></View>{profile.goal===goal&&<Check size={20}/>}</Card></Pressable>)}</View>}
{step===1&&<><Field label="Daily calories" value={String(profile.targets.calories)} number onChangeText={v=>update({targets:{...profile.targets,calories:Number(v)}})}/><Button secondary onPress={()=>setCalculator(!calculator)}>{calculator?'Hide calculator':'Recommend a starting point'}</Button>{calculator&&<Card style={{gap:16}}><View style={s.row}><Field label="Age (18+)" value={age} number onChangeText={setAge}/><Field label="Height (cm)" value={height} number onChangeText={setHeight}/><Field label="Weight (kg)" value={weight} number onChangeText={setWeight}/></View><P style={{fontSize:12,color:C.muted}}>Sex used in the calorie equation</P><View style={s.wrap}>{(['female','male'] as const).map(v=><Chip key={v} label={v} selected={sex===v} onPress={()=>setSex(v)}/>)}</View><P style={{fontFamily:'DMSans_700Bold'}}>Typical activity</P><View style={s.wrap}>{['Mostly seated','Lightly active','Moderately active','Very active'].map((l,i)=><Chip key={l} label={l} selected={activity===[1.2,1.375,1.55,1.725][i]} onPress={()=>setActivity([1.2,1.375,1.55,1.725][i])}/>)}</View><Button onPress={()=>{try{update({targets:recommendedTargets(Number(age),sex,Number(height),Number(weight),activity,profile.goal)});setError('');setCalculator(false);}catch(e){setError((e as Error).message);}}}>Use my estimate</Button><P style={{fontSize:11,color:C.muted}}>An editable starting estimate using Mifflin–St Jeor, activity, and goal. Individual needs vary.</P></Card>}</>}
{step===2&&<><View style={{gap:16}}>{(['protein','carbs','fat'] as const).map(key=><Field key={key} label={`${key[0].toUpperCase()+key.slice(1)} (grams)`} value={String(profile.targets[key])} number onChangeText={v=>update({targets:{...profile.targets,[key]:Number(v)}})}/>)}</View><Card style={{backgroundColor:C.soft,gap:12}}><H size={28}>{macroCalories.toLocaleString()} kcal</H><P style={{color:C.muted}}>Calculated from your macros · calorie target {profile.targets.calories}</P>{macroCalories!==profile.targets.calories&&<Button secondary small onPress={()=>update({targets:{...profile.targets,calories:macroCalories}})}>Use {macroCalories} as my calorie target</Button>}</Card><Button secondary onPress={()=>{const c=profile.targets.calories;update({targets:{calories:c,protein:Math.round(c*.3/4),carbs:Math.round(c*.4/4),fat:Math.round(c*.3/9)}});}}>Recommend for me</Button></>}
{step===3&&<View style={{paddingVertical:36,gap:25}}><Stepper value={profile.people} onChange={people=>update({people})} label={profile.people===1?'Just me':'people at the table'}/><P style={{textAlign:'center',color:C.muted}}>Portions and grocery quantities scale automatically.</P></View>}
{step===4&&<><View style={s.wrap}>{MEALS.map(m=><Chip key={m} label={m==='Snack'?'Snacks':m} selected={profile.meals.includes(m)} onPress={()=>update({meals:toggle(profile.meals,m)})}/>)}</View><H size={20}>Leave room for the rest</H><P style={{color:C.muted}}>Daily target allocation, including meals you won’t plan here. Percentages must total 100%.</P><View style={{gap:12}}>{MEALS.map(m=><Field key={m} label={`${m} (%)`} value={String(Math.round(profile.allocations[m]*100))} number onChangeText={v=>update({allocations:{...profile.allocations,[m]:Number(v)/100}})}/>)}</View><H size={20}>Different days, different meals?</H><View style={s.wrap}>{DAYS.map((d,i)=><Chip key={d} label={d.slice(0,3)} selected={customDay===i} onPress={()=>setCustomDay(customDay===i?null:i)}/>)}</View>{customDay!==null&&<Card style={{gap:14}}><P>{DAYS[customDay]}</P><View style={s.wrap}>{MEALS.map(m=><Chip key={m} label={m} selected={(profile.dayMeals[customDay]??profile.meals).includes(m)} onPress={()=>update({dayMeals:{...profile.dayMeals,[customDay]:toggle(profile.dayMeals[customDay]??profile.meals,m)}})}/>)}</View></Card>}</>}
{step===5&&<><View style={{gap:10}}>{DAYS.map((d,i)=><Pressable accessibilityRole="checkbox" accessibilityState={{checked:profile.days.includes(i)}} key={d} onPress={()=>update({days:toggle(profile.days,i)})}><Card style={[s.between,{padding:18,backgroundColor:profile.days.includes(i)?C.soft:C.paper}]}><P style={{fontFamily:'DMSans_700Bold'}}>{d}</P>{profile.days.includes(i)&&<Check size={18}/>}</Card></Pressable>)}</View><P style={{color:C.muted,textAlign:'center'}}>{profile.days.length} days selected</P></>}
{step===6&&<><View style={{alignItems:'center',paddingVertical:25}}><H size={72}>${profile.budget}</H><P style={{color:C.muted,marginTop:8}}>for the week, for everyone</P></View><View style={{height:32,justifyContent:'center'}}><View style={{height:7,borderRadius:5,backgroundColor:C.line}}/><View style={{position:'absolute',height:7,borderRadius:5,backgroundColor:C.lime,width:`${Math.min(100,Math.max(0,(profile.budget-40)/210*100))}%`}}/><View style={{position:'absolute',left:0,right:0,height:44,flexDirection:'row'}}>{Array.from({length:22},(_,i)=><Pressable key={i} accessibilityRole="button" accessibilityLabel={`Set budget to ${40+i*10} dollars`} onPress={()=>update({budget:40+i*10})} style={{flex:1}}/>)}</View></View><View style={s.between}><P style={{color:C.muted}}>$40</P><P style={{color:C.muted}}>$250+</P></View><Field label="Or enter your weekly budget ($)" value={String(profile.budget)} number onChangeText={v=>update({budget:Number(v)})}/></>}
{step===7&&<><View style={s.wrap}>{PREFERENCES.map(pref=><Chip key={pref} label={pref} selected={profile.preferences.includes(pref)} onPress={()=>{if(!profile.preferences.includes(pref)&&profile.preferences.length>=3){setError('Choose up to three. Tap a selected preference to remove it.');return;}setError('');update({preferences:toggle(profile.preferences,pref)});}}/>)}</View><P style={{color:C.muted}}>{profile.preferences.length} of 3 selected</P></>}
{step===8&&<><View style={s.wrap}><Chip label="None" selected={!profile.diets.length} onPress={()=>update({diets:[]})}/>{DIETS.map(d=><Chip key={d} label={d} selected={profile.diets.includes(d)} onPress={()=>update({diets:toggle(profile.diets,d)})}/>)}</View><H size={20}>Allergies & ingredients to exclude</H><P style={{color:C.muted}}>These are always excluded, including in swaps.</P><View style={s.wrap}>{['milk','egg','peanut','tree nuts','soy','wheat','gluten','shellfish','fish','sesame'].map(a=><Chip key={a} label={a} selected={profile.allergies.includes(a)} onPress={()=>update({allergies:toggle(profile.allergies,a)})}/>)}</View><Field label="Other exclusions, separated by commas" value={profile.avoid.filter(a=>!INGREDIENTS.some(i=>i.id===a)).join(', ')} onChangeText={v=>update({avoid:[...profile.avoid.filter(a=>INGREDIENTS.some(i=>i.id===a)),...v.split(',').map(x=>x.trim().toLowerCase())]})}/></>}
{step===9&&<><Field placeholder="Search chicken, rice, eggs…" value={search} onChangeText={setSearch}/><View style={{gap:10}}>{INGREDIENTS.filter(i=>i.name.toLowerCase().includes(search.toLowerCase())).slice(0,search?30:12).map(i=><Card key={i.id} style={{padding:16,gap:12}}><P style={{fontFamily:'DMSans_700Bold'}}>{i.name}</P><View style={s.wrap}>{['Love','Okay','Avoid'].map(v=><Chip key={v} label={v} selected={v==='Love'?profile.love.includes(i.id):v==='Avoid'?profile.avoid.includes(i.id):!profile.love.includes(i.id)&&!profile.avoid.includes(i.id)} onPress={()=>update({love:v==='Love'?[...profile.love.filter(x=>x!==i.id),i.id]:profile.love.filter(x=>x!==i.id),avoid:v==='Avoid'?[...profile.avoid.filter(x=>x!==i.id),i.id]:profile.avoid.filter(x=>x!==i.id)})}/>)}</View></Card>)}</View></>}
{step===10&&<View style={{flexDirection:'row',flexWrap:'wrap',gap:14}}>{EQUIPMENT.map((e,i)=>{const Icon=[ChefHat,Flame,Microwave,Wind,Utensils,CookingPot,Blender][i];return <Pressable accessibilityRole="checkbox" accessibilityState={{checked:profile.equipment.includes(e)}} key={e} onPress={()=>update({equipment:toggle(profile.equipment,e)})} style={{width:'47%',flexGrow:1,backgroundColor:profile.equipment.includes(e)?C.soft:C.paper,borderWidth:1,borderColor:profile.equipment.includes(e)?'#C6D6AD':C.line,borderRadius:22,padding:24,alignItems:'center',gap:14}}><View style={{backgroundColor:profile.equipment.includes(e)?C.lime:'#F5F3EB',width:68,height:68,borderRadius:24,alignItems:'center',justifyContent:'center'}}><Icon size={37} strokeWidth={1.3}/></View><P style={{fontFamily:'DMSans_700Bold'}}>{e}</P>{profile.equipment.includes(e)&&<Check size={15}/>}</Pressable>;})}</View>}
{step===11&&<><View style={s.wrap}>{[{name:'Under 15 minutes',value:14},{name:'15–30 minutes',value:30},{name:'30–60 minutes',value:60},{name:'Don’t care',value:180}].map(t=><Chip key={t.name} label={t.name} selected={profile.maxMinutes===t.value} onPress={()=>update({maxMinutes:t.value})}/>)}</View><H size={22} style={{marginTop:15}}>How often will you meal prep?</H><Stepper value={profile.prepSessions} min={0} max={7} onChange={prepSessions=>update({prepSessions})} label="times per week"/></>}
{step===12&&<><Field label="What should we call you?" value={profile.name} onChangeText={name=>update({name})}/><Card style={{gap:16}}>{[['Your goal',profile.goal],['Daily energy',`${profile.targets.calories} kcal`],['Your macros',`${profile.targets.protein}g P · ${profile.targets.carbs}g C · ${profile.targets.fat}g F`],['Your table',`${profile.people} people · ${profile.days.length} days`],['Grocery budget',`$${profile.budget} / week`],['Cooking',`${profile.maxMinutes===180?'Flexible':`Up to ${profile.maxMinutes} min`} · ${profile.prepSessions} prep sessions`],['Preferences',profile.preferences.join(', ')],['Diet',profile.diets.join(', ')||'No dietary restrictions']].map(([a,b])=><View key={a} style={s.between}><P style={{color:C.muted,flex:1}}>{a}</P><P style={{fontFamily:'DMSans_700Bold',flex:1,textAlign:'right'}}>{b}</P></View>)}</Card>{!configured&&<P style={{fontSize:12,color:C.muted}}>This build is in sample mode. Your personalized sample plan is calculated locally and saved on this device.</P>}</>}
{error&&<P accessibilityRole="alert" style={{color:'#9B543C'}}>{error}</P>}<Button testID="onboarding-next" onPress={step===12?()=>void build():next}>{step===12?'Build my week':'Continue'}</Button><P style={{color:C.muted,fontSize:11,textAlign:'center'}}>You can change all of this later.</P></ScrollView><AuthSheet visible={auth} onClose={()=>setAuth(false)}/></View>;
}
