import React from 'react';
import { ActivityIndicator, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions, KeyboardAvoidingView } from 'react-native';
import { ArrowRight, X, Check, Plus, Minus, Sparkles, ChevronRight } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
export const C={bg:'#F7F8F2',paper:'#FFFFFF',ink:'#19221D',muted:'#798078',line:'#E6E9E0',lime:'#D5F570',soft:'#EEF3E4',dark:'#24362B',orange:'#F2BB80'};
export const money=(n:number)=>`$${n.toFixed(2)}`;
export const round=(n:number)=>Math.round(n);
export function P({children,style,...props}:React.ComponentProps<typeof Text>){return <Text {...props} style={[{fontFamily:'DMSans_400Regular',fontSize:14,lineHeight:21,color:C.ink},style]}>{children}</Text>;}
export function H({children,size=28,style}: {children:React.ReactNode;size?:number;style?:any}){return <P style={[{fontFamily:'Manrope_700Bold',fontSize:size,lineHeight:size*1.18,letterSpacing:-size*.035},style]}>{children}</P>;}
export function Eyebrow({children,style}:{children:React.ReactNode;style?:any}){return <P style={[{fontSize:10,letterSpacing:1.6,fontFamily:'DMSans_700Bold',color:C.muted,lineHeight:16},style]}>{children}</P>;}
export function Card({children,style}:{children:React.ReactNode;style?:any}){return <View style={[s.card,style]}>{children}</View>;}
export function Button({children,onPress,secondary=false,small=false,disabled=false,icon=true,style,testID}:{children:React.ReactNode;onPress:()=>void;secondary?:boolean;small?:boolean;disabled?:boolean;icon?:boolean;style?:any;testID?:string}){return <Pressable accessibilityRole="button" testID={testID} disabled={disabled} onPress={onPress} style={({pressed})=>[{backgroundColor:secondary?C.paper:C.ink,borderRadius:14,minHeight:small?44:52,paddingHorizontal:small?16:20,paddingVertical:12,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:12,borderWidth:secondary?1:0,borderColor:C.line,opacity:disabled?.4:pressed?.75:1},style]}><P style={{fontFamily:'DMSans_700Bold',fontSize:13,color:secondary?C.ink:C.paper}}>{children}</P>{icon&&<ArrowRight size={16} color={secondary?C.ink:C.paper}/>}</Pressable>;}
export function Chip({label,selected,onPress,icon}:{label:string;selected?:boolean;onPress:()=>void;icon?:React.ReactNode}){return <Pressable accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={({pressed})=>[s.chip,{backgroundColor:selected?C.lime:C.paper,borderColor:selected?C.lime:C.line,opacity:pressed?.7:1}]}>{icon}{selected&&<Check size={14} color={C.ink}/>}<P style={{fontSize:13,fontFamily:selected?'DMSans_700Bold':'DMSans_500Medium'}}>{label}</P></Pressable>;}
export function Field({label,value,onChangeText,placeholder,number=false,multiline=false,testID}:{label?:string;value:string;onChangeText:(v:string)=>void;placeholder?:string;number?:boolean;multiline?:boolean;testID?:string}) {return <View style={{gap:7,flexGrow:1}}>{label&&<P style={{fontSize:12,fontFamily:'DMSans_700Bold'}}>{label}</P>}<TextInput accessibilityLabel={label??placeholder} testID={testID} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={C.muted} keyboardType={number?'decimal-pad':'default'} multiline={multiline} style={[s.input,multiline&&{height:100,textAlignVertical:'top'}]}/></View>;}
export function Stepper({value,onChange,min=1,max=20,label}:{value:number;onChange:(n:number)=>void;min?:number;max?:number;label?:string}){return <View style={{alignItems:'center',gap:12}}><View style={{flexDirection:'row',alignItems:'center',gap:36}}><Pressable accessibilityLabel="Decrease" accessibilityRole="button" onPress={()=>onChange(Math.max(min,value-1))} style={s.step}><Minus size={22}/></Pressable><H size={80}>{value}</H><Pressable accessibilityLabel="Increase" accessibilityRole="button" onPress={()=>onChange(Math.min(max,value+1))} style={s.step}><Plus size={22}/></Pressable></View>{label&&<P style={{color:C.muted}}>{label}</P>}</View>;}
export function Sheet({visible,onClose,title,subtitle,children}:{visible:boolean;onClose:()=>void;title:string;subtitle?:string;children:React.ReactNode}){const {width}=useWindowDimensions();return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1,backgroundColor:'#15221B66',justifyContent:width>700?'center':'flex-end',alignItems:'center'}}><SafeAreaView edges={['bottom','top']} style={{width:'100%',maxWidth:620,maxHeight:'96%',backgroundColor:C.bg,borderRadius:width>700?28:28,overflow:'hidden'}}><View style={{padding:24,paddingBottom:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:16}}><View style={{flex:1}}><H size={26}>{title}</H>{subtitle&&<P style={{color:C.muted,marginTop:8}}>{subtitle}</P>}</View><Pressable accessibilityRole="button" accessibilityLabel="Close" onPress={onClose} style={s.step}><X size={20}/></Pressable></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:24,paddingTop:8,gap:20,paddingBottom:40}}>{children}</ScrollView></SafeAreaView></KeyboardAvoidingView></Modal>;}
export function Empty({title,body,action}:{title:string;body:string;action?:React.ReactNode}){return <Card style={{alignItems:'center',gap:16,padding:32}}><Sparkles size={30} color={C.muted}/><H size={21}>{title}</H><P style={{textAlign:'center',color:C.muted}}>{body}</P>{action}</Card>;}
export function Busy({label='Working on it…'}:{label?:string}){return <View style={{padding:40,gap:20,alignItems:'center'}}><ActivityIndicator size="large" color={C.dark}/><P>{label}</P></View>;}
export const s=StyleSheet.create({card:{backgroundColor:C.paper,borderWidth:1,borderColor:C.line,borderRadius:22,padding:22},row:{flexDirection:'row',alignItems:'center',gap:12},between:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{minHeight:44,borderWidth:1,borderRadius:13,paddingHorizontal:14,paddingVertical:11,flexDirection:'row',alignItems:'center',gap:7},input:{backgroundColor:C.paper,borderWidth:1,borderColor:C.line,borderRadius:13,padding:15,minHeight:50,color:C.ink,fontFamily:'DMSans_400Regular',fontSize:15},step:{width:44,height:44,borderRadius:22,backgroundColor:C.soft,alignItems:'center',justifyContent:'center'},section:{gap:20,marginBottom:28}});
